# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва предмету')),
                ('datetime', models.DateTimeField(verbose_name='Дата і час проведення')),
                ('teacher', models.CharField(max_length=256, verbose_name='ПІБ викладача')),
                ('exam_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Іспит',
                'verbose_name_plural': 'Іспити',
            },
        ),
    ]
